# Generated by Django 4.2.7 on 2026-06-28 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('successful', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Login activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=10)),
                ('primary_color', models.CharField(default='#3b82f6', help_text='Hex color code for theme', max_length=7)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('ui_animations', models.BooleanField(default=True)),
                ('default_output_format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('jpg', 'JPG')], default='pdf', max_length=5)),
                ('compression_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=10)),
                ('auto_page_size', models.CharField(choices=[('a4', 'A4'), ('letter', 'Letter'), ('fit', 'Fit to Image')], default='a4', max_length=10)),
                ('auto_rotate', models.BooleanField(default=True)),
                ('file_history_enabled', models.BooleanField(default=True)),
                ('auto_delete_after', models.CharField(choices=[('never', 'Never'), ('1hour', '1 Hour'), ('24hours', '24 Hours'), ('7days', '7 Days')], default='never', max_length=10)),
                ('storage_used', models.BigIntegerField(default=0)),
                ('storage_limit', models.BigIntegerField(default=104857600)),
                ('email_notifications', models.BooleanField(default=True)),
                ('conversion_alerts', models.BooleanField(default=True)),
                ('toast_notifications', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=30, help_text='Session timeout in minutes')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('login_activity_log', models.TextField(blank=True, null=True)),
                ('total_conversions', models.IntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersettings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='filehistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='filehistory',
            name='file_size',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='filehistory',
            name='file_type',
            field=models.CharField(blank=True, default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='filehistory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filehistory',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
