# Generated by Django 5.2.15 on 2026-07-02 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_loginactivity_usersettings_alter_filehistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Settings', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='login_activity_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='primary_color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='session_timeout',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='storage_limit',
            field=models.PositiveBigIntegerField(default=104857600),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='storage_used',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='total_conversions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='total_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
