# Generated by Django 4.2.7 on 2026-07-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehistory',
            name='conversion_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
