"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

from pathlib import Path

# Base Directory

BASE_DIR = Path(__file__).resolve().parent.parent

# Security

SECRET_KEY = 'django-insecure-$blctps7u77p8a_m)5a4z9j(ki8=f8m1&r1j@8idc4$8qw9qq4'

DEBUG = True

ALLOWED_HOSTS = []

# Installed Apps

INSTALLED_APPS = [
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'core',
]

# Login Settings

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Middleware

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

# Templates

TEMPLATES = [
{
'BACKEND': 'django.template.backends.django.DjangoTemplates',
'DIRS': [BASE_DIR / 'core' / 'templates'],
'APP_DIRS': True,
'OPTIONS': {
'context_processors': [
'django.template.context_processors.request',
'django.contrib.auth.context_processors.auth',
'django.contrib.messages.context_processors.messages',
],
},
},
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# Database

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.sqlite3',
'NAME': BASE_DIR / 'db.sqlite3',
}
}

# Password Validation

AUTH_PASSWORD_VALIDATORS = [
{
'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
},
]

# Email Configuration (Gmail SMTP)
# ===============================
# IMPORTANT: For Gmail, you MUST use an App Password, NOT your regular Gmail password.
#
# How to create a Gmail App Password:
# 1. Go to: https://myaccount.google.com/security
# 2. Enable "2-Step Verification" (required for App Passwords)
# 3. Go to: https://myaccount.google.com/apppasswords
# 4. Select "Mail" and "Windows Computer" (or your device)
# 5. Click "Generate"
# 6. Copy the 16-character password (shown once only)
# 7. Paste it below as EMAIL_HOST_PASSWORD
#
# NOTE: The current EMAIL_HOST_PASSWORD shown below is a placeholder.
#       Replace it with your actual 16-character Gmail App Password.
#       The regular Gmail password "Aayush@123" will NOT work with SMTP.

# AFTER (Correct & Secure)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ayush98050@gmail.com'
EMAIL_HOST_PASSWORD = 'ggxicvnpssuoiivz'  # <--- Put your 16-character App Password here

# For console-based testing (no real email sent):
# Uncomment the line below and comment out the SMTP settings above to test locally:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static Files

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static'
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media Files

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default Primary Key

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DOMAIN = "aipdfstudio.com"
SITE_NAME = "AI PDF Studio Pro"
DEFAULT_FROM_EMAIL = "AI PDF Studio Pro <ayush98050@gmail.com>"